-- 1. Xóa dữ liệu cũ và reset identity
DELETE FROM Brands;
DBCC CHECKIDENT('Brands', RESEED, 0);

-- 2. Bật cho phép insert explicit Id nếu cột Id là identity
SET IDENTITY_INSERT Brands ON;

-- 3. Insert 24 brand với DisplayOrder = Id và Image theo thứ tự 1.png, 2.png, ...
INSERT INTO Brands (
    Id, Name, ShortName, Description, FullDescription, Founded, Origin, Website, Image, Features,
    DisplayOrder, IsActive, IsFeatured, CreatedAt, UpdatedAt
) VALUES
-- 1. PROAD
(1,
 N'PROAD',
 N'PRD',
 N'Thương hiệu chăm sóc thú cưng từ thảo mộc tự nhiên của Thái Lan',
 N'PROAD là thương hiệu Thái Lan chuyên về các sản phẩm vệ sinh và chăm sóc thú cưng như xịt kháng khuẩn, rửa tai, dưỡng da và dung dịch lau sàn. Các sản phẩm của PROAD sử dụng chiết xuất thảo mộc tự nhiên như nghệ, hoa cúc, đinh hương, Andrographis… đảm bảo an toàn tuyệt đối cho chó và mèo, kể cả khi liếm phải. Không chứa cồn, sulfate hay chất bảo quản độc hại, PROAD mang đến giải pháp chăm sóc toàn diện, thân thiện và hiệu quả.',
 2020,
 N'Thái Lan',
 N'https://petclub.co.th/en/product/brand/PROAD',
 N'/images/brands/1.png',
 N'["Chiết xuất thảo mộc tự nhiên","Không cồn, không sulfate","Dùng được cho cả chó và mèo","An toàn nếu thú cưng liếm phải","Làm sạch và kháng khuẩn nhẹ nhàng","Chăm sóc da nhạy cảm","Thích hợp sử dụng hằng ngày","Sản xuất tại Thái Lan"]',
 1, 1, 1, GETDATE(), GETDATE()
),
-- 2. Moochie
(2,
 N'Moochie',
 N'MCH',
 N'Thương hiệu thức ăn cao cấp cho chó mèo với công thức dinh dưỡng cá nhân hóa',
 N'Moochie là thương hiệu thức ăn ướt và snack cao cấp dành cho cả chó và mèo, được nghiên cứu bởi chuyên gia dinh dưỡng theo tiêu chuẩn AAFCO và GMP. Các sản phẩm của Moochie sử dụng nguyên liệu tự nhiên như cá hồi, cranberry, goji berry… không chứa GMO hay chất bảo quản độc hại. Moochie cung cấp thực đơn đa dạng, chia theo độ tuổi, cân nặng, tình trạng sức khỏe, mang đến giải pháp dinh dưỡng chuyên biệt cho từng thú cưng.',
 2019,
 N'Thái Lan',
 N'https://www.moochiepetfood.com/',
 N'/images/brands/2.png',
 N'["Công thức chuẩn AAFCO","Thành phần superfood","Không GMO, không chất bảo quản","Dành cho cả chó và mèo","Dinh dưỡng cá nhân hóa","Sản phẩm đa dạng theo nhu cầu sức khỏe","Chứng nhận GMP, HACCP, BRCGS","Được xuất khẩu toàn cầu"]',
 2, 1, 1, GETDATE(), GETDATE()
),
-- 3. JerHigh
(3,
 N'JerHigh',
 N'JRH',
 N'Thương hiệu snack cho chó hàng đầu Thái Lan',
 N'JerHigh là thương hiệu snack dành cho chó hàng đầu tại Thái Lan, nổi tiếng với các sản phẩm snack từ thịt gà thật (human‑grade), đáp ứng tiêu chuẩn an toàn xuất khẩu và dinh dưỡng cao. JerHigh đạt vị trí số 1 tại thị trường snack chó và được nhiều gia đình tin dùng.',
 2002,
 N'Thái Lan',
 N'https://www.jerhigh.com/',
 N'/images/brands/3.png',
 N'["Snack từ thịt gà thật","Human-grade","Nhập khẩu tiêu chuẩn","Snack số 1 Thái Lan","Dinh dưỡng cao","Đa dạng hương vị","Xuất khẩu quốc tế","Hỗ trợ sức khỏe răng miệng"]',
 3, 1, 1, GETDATE(), GETDATE()
),
-- 4. Me‑O
(4,
 N'Me‑O',
 N'MEO',
 N'Thương hiệu thức ăn mèo cân bằng dinh dưỡng từ Thái Lan',
 N'Me‑O là thương hiệu thức ăn mèo đến từ Perfect Companion Group (Thái Lan), với các sản phẩm khô, ướt đạt tiêu chuẩn cao, dễ tiêu hóa và giàu dinh dưỡng. Sản xuất tại cơ sở đạt chuẩn quốc tế, Me‑O được nhiều chủ nuôi tin dùng.',
 1979,
 N'Thái Lan',
 N'https://perfectcompanion.com',
 N'/images/brands/4.png',
 N'["Thức ăn mèo cân bằng","Khô & ướt","Tiêu chuẩn quốc tế","Nhà sản xuất PCG","Dễ tiêu hóa","Được tin dùng rộng rãi","Hương vị hấp dẫn","Giá cả hợp lý"]',
 4, 1, 1, GETDATE(), GETDATE()
),
-- 5. SmartHeart
(5,
 N'SmartHeart',
 N'SMH',
 N'Thương hiệu thức ăn cho thú cưng thuộc Perfect Companion Group',
 N'SmartHeart là thương hiệu thức ăn cho cả chó và mèo thuộc Perfect Companion Group của C.P. Group Thái Lan. Sản phẩm đa dạng gồm thức ăn khô & ướt, các dòng chuyên biệt theo lứa tuổi và kích cỡ, được sản xuất theo tiêu chuẩn GMP/HACCP và xuất khẩu nhiều nước.',
 1980,
 N'Thái Lan',
 N'https://smartheart.my/',
 N'/images/brands/5.png',
 N'["Dành cho chó & mèo","Khô & ướt","Chuyên biệt theo nhu cầu","Tiêu chuẩn GMP/HACCP","Thuộc PCG - C.P. Group","Được tin dùng khu vực Southeast Asia","Hỗ trợ sức khỏe tim mạch","Dễ tiêu hóa"]',
 5, 1, 1, GETDATE(), GETDATE()
),
-- 6. Kit Cat
(6,
 N'Kit Cat',
 N'KTC',
 N'Thương hiệu chăm sóc mèo tự nhiên từ Singapore',
 N'Kit Cat International (Singapore, 2013) chuyên cung cấp các sản phẩm tự nhiên cho mèo như thức ăn, snack, litter. Được sáng lập bởi hai anh em yêu mèo và cam kết sử dụng nguyên liệu sạch, lành mạnh với tiêu chuẩn cao.',
 2013,
 N'Singapore',
 N'https://kitcat.in.th/',
 N'/images/brands/6.png',
 N'["Sản phẩm cho mèo","Nguyên liệu tự nhiên","Thức ăn & snack & litter","Thương hiệu từ Singapore","Được cộng đồng yêu mèo tin dùng","Thân thiện với môi trường","Hỗ trợ sức khỏe đường ruột","Chất lượng cao"]',
 6, 1, 0, GETDATE(), GETDATE()
),
-- 7. Royal Canin
(7,
 N'Royal Canin',
 N'RCN',
 N'Thương hiệu thức ăn cao cấp cho chó mèo',
 N'Royal Canin là thương hiệu thức ăn cao cấp hàng đầu thế giới, chuyên nghiên cứu và phát triển các sản phẩm dinh dưỡng tối ưu cho từng giống chó mèo cụ thể. Với hơn 50 năm kinh nghiệm, Royal Canin cam kết mang đến những sản phẩm chất lượng cao nhất cho thú cưng của bạn.',
 1968,
 N'Pháp',
 N'http://www.royalcanin.com',
 N'/images/brands/7.png',
 N'["Thức ăn chuyên biệt theo giống loài","Công thức dinh dưỡng khoa học","Hỗ trợ sức khỏe toàn diện","Sản phẩm cho mọi lứa tuổi","Chất lượng được kiểm định nghiêm ngặt","Nghiên cứu bởi đội ngũ chuyên gia","Đa dạng sản phẩm","Được tin dùng toàn cầu"]',
 7, 1, 1, GETDATE(), GETDATE()
),
-- 8. Pedigree
(8,
 N'Pedigree',
 N'PDG',
 N'Thức ăn cho chó chất lượng cao',
 N'Pedigree là thương hiệu thức ăn cho chó nổi tiếng với chất lượng cao và giá cả hợp lý. Với hơn 80 năm kinh nghiệm, Pedigree đã trở thành lựa chọn tin cậy của hàng triệu chủ nuôi trên toàn thế giới.',
 1935,
 N'Mỹ',
 N'http://www.pedigree.com',
 N'/images/brands/8.png',
 N'["Thức ăn cân bằng dinh dưỡng","Hỗ trợ sức khỏe răng miệng","Tăng cường hệ miễn dịch","Sản phẩm cho mọi kích thước chó","Giá cả hợp lý","Chất lượng ổn định","Dễ tiêu hóa","Hương vị hấp dẫn"]',
 8, 1, 1, GETDATE(), GETDATE()
),
-- 9. Purina
(9,
 N'Purina',
 N'PRN',
 N'Thương hiệu thức ăn đa dạng',
 N'Purina là thương hiệu thức ăn thú cưng đa dạng với nhiều dòng sản phẩm khác nhau. Từ thức ăn cao cấp đến bình dân, Purina đáp ứng mọi nhu cầu của thú cưng và chủ nuôi.',
 1894,
 N'Mỹ',
 N'http://www.purina.com',
 N'/images/brands/9.png',
 N'["Đa dạng sản phẩm","Chất lượng cao","Giá cả cạnh tranh","Hỗ trợ sức khỏe toàn diện","Công thức dinh dưỡng khoa học","Sản phẩm cho mọi lứa tuổi","Dễ tiêu hóa","Được tin dùng rộng rãi"]',
 9, 1, 0, GETDATE(), GETDATE()
),
-- 10. Whiskas
(10,
 N'Whiskas',
 N'WKS',
 N'Thức ăn cho mèo nổi tiếng',
 N'Whiskas là thương hiệu thức ăn cho mèo được yêu thích trên toàn thế giới. Với hơn 50 năm kinh nghiệm, Whiskas hiểu rõ nhu cầu dinh dưỡng của mèo và mang đến những sản phẩm chất lượng cao.',
 1958,
 N'Anh',
 N'http://www.whiskas.com',
 N'/images/brands/10.png',
 N'["Thức ăn chuyên biệt cho mèo","Hương vị hấp dẫn","Dinh dưỡng cân bằng","Hỗ trợ sức khỏe mèo","Sản phẩm đa dạng","Chất lượng ổn định","Dễ tiêu hóa","Được mèo yêu thích"]',
 10, 1, 0, GETDATE(), GETDATE()
),
-- 11. Hill's
(11,
 N'Hill''s',
 N'HLS',
 N'Thức ăn thú y chuyên nghiệp',
 N'Hill''s Science Diet là thương hiệu thức ăn thú y chuyên nghiệp, được phát triển bởi các bác sĩ thú y. Sản phẩm của Hill''s được thiết kế để hỗ trợ điều trị và phòng ngừa các vấn đề sức khỏe của thú cưng.',
 1939,
 N'Mỹ',
 N'http://www.hills.com',
 N'/images/brands/11.png',
 N'["Công thức thú y chuyên nghiệp","Hỗ trợ điều trị bệnh","Dinh dưỡng khoa học","Được bác sĩ thú y khuyến nghị","Sản phẩm chuyên biệt","Chất lượng cao cấp","An toàn cho thú cưng","Hiệu quả đã được chứng minh"]',
 11, 1, 0, GETDATE(), GETDATE()
),
-- 12. Nutri-Source
(12,
 N'Nutri-Source',
 N'NTS',
 N'Thức ăn tự nhiên cao cấp',
 N'Nutri-Source là thương hiệu thức ăn tự nhiên cao cấp, tập trung vào việc sử dụng các nguyên liệu tự nhiên và công thức dinh dưỡng tối ưu. Sản phẩm của Nutri-Source giúp thú cưng khỏe mạnh và tràn đầy năng lượng.',
 1986,
 N'Mỹ',
 N'http://www.nutri-source.com',
 N'/images/brands/12.png',
 N'["Nguyên liệu tự nhiên","Không chứa chất bảo quản nhân tạo","Dinh dưỡng tối ưu","Hỗ trợ tiêu hóa","Tăng cường năng lượng","Sản phẩm cao cấp","An toàn tuyệt đối","Hiệu quả lâu dài"]',
 12, 1, 0, GETDATE(), GETDATE()
),
-- 13. Acana
(13,
 N'Acana',
 N'ACN',
 N'Thức ăn sinh học tự nhiên',
 N'Acana là thương hiệu thức ăn sinh học tự nhiên, được sản xuất theo phương pháp truyền thống với các nguyên liệu tươi ngon. Acana cam kết mang đến những sản phẩm chất lượng cao nhất cho thú cưng.',
 1975,
 N'Canada',
 N'http://www.acana.com',
 N'/images/brands/13.png',
 N'["Nguyên liệu tươi ngon","Công thức sinh học","Không chứa ngũ cốc","Protein cao cấp","Dinh dưỡng tự nhiên","Hỗ trợ sức khỏe toàn diện","Sản phẩm cao cấp","Được tin dùng toàn cầu"]',
 13, 1, 0, GETDATE(), GETDATE()
),
-- 14. Orijen
(14,
 N'Orijen',
 N'ORJ',
 N'Thức ăn hoang dã tự nhiên',
 N'Orijen là thương hiệu thức ăn hoang dã tự nhiên, được thiết kế để mô phỏng chế độ ăn tự nhiên của thú cưng trong môi trường hoang dã. Sản phẩm của Orijen giúp thú cưng phát triển khỏe mạnh và tự nhiên.',
 1985,
 N'Canada',
 N'http://www.orijen.com',
 N'/images/brands/14.png',
 N'["Công thức hoang dã tự nhiên","Nguyên liệu tươi sống","Protein động vật cao","Không chứa ngũ cốc","Dinh dưỡng tự nhiên","Hỗ trợ phát triển tự nhiên","Sản phẩm cao cấp","Được chứng minh hiệu quả"]',
 14, 1, 0, GETDATE(), GETDATE()
),
-- 15. Natural Core
(15,
 N'Natural Core',
 N'NCR',
 N'Thức ăn hữu cơ tự nhiên',
 N'Natural Core là thương hiệu thức ăn hữu cơ tự nhiên, tập trung vào việc sử dụng các nguyên liệu hữu cơ và phương pháp sản xuất thân thiện với môi trường. Sản phẩm của Natural Core tốt cho thú cưng và môi trường.',
 2003,
 N'Hàn Quốc',
 N'http://www.naturalcore.com',
 N'/images/brands/15.png',
 N'["Nguyên liệu hữu cơ","Thân thiện môi trường","Dinh dưỡng tự nhiên","Không chứa hóa chất","Hỗ trợ sức khỏe toàn diện","Sản phẩm chất lượng cao","An toàn tuyệt đối","Bảo vệ môi trường"]',
 15, 1, 0, GETDATE(), GETDATE()
),
-- 16. Sheba
(16,
 N'Sheba',
 N'SHB',
 N'Thương hiệu thức ăn cao cấp cho mèo & chó thuộc Mars, nổi tiếng toàn cầu',
 N'Sheba là thương hiệu thức ăn cho mèo và chó cao cấp của Mars, với các dòng pate & wet food tiện dụng, hương vị hấp dẫn, dinh dưỡng cân bằng. Sản phẩm được thiết kế để đáp ứng khẩu vị và nhu cầu dinh dưỡng của thú cưng hàng ngày, dễ dàng phục vụ chủ nuôi bận rộn. Sheba được bán rộng rãi và tin dùng bởi nhiều gia đình trên thế giới.',
 1982,
 N'Mỹ',
 N'http://www.sheba.com',
 N'/images/brands/16.png',
 N'["Thức ăn wet food cao cấp","Dạng pate tiện dụng","Hương vị đa dạng hấp dẫn","Dinh dưỡng cân bằng","Thiết kế phục vụ người bận rộn","Được tin dùng toàn cầu","Sản phẩm dễ mua tại nhiều thị trường","Chất lượng từ Mars"]',
 16, 1, 1, GETDATE(), GETDATE()
),
-- 17. Taste of the Wild
(17,
 N'Taste of the Wild',
 N'TOW',
 N'Thức ăn tự nhiên chất lượng cao từ Mỹ',
 N'Taste of the Wild là thương hiệu thức ăn cao cấp không chứa ngũ cốc, sử dụng nguồn protein từ thịt game, cá hồi và thịt bò hoang dã. Phù hợp với chế độ ăn tự nhiên của chó, mèo. Có nhiều dòng chuyên biệt về tuổi, kích cỡ và yêu cầu sức khỏe.',
 2007,
 N'Mỹ',
 N'https://www.tasteofthewildpetfood.com/',
 N'/images/brands/17.png',
 N'["Grain-free","Protein từ thịt hoang dã","Thành phần tự nhiên","Chống dị ứng","Dinh dưỡng toàn diện","Phân theo độ tuổi","Phù hợp chó mèo","Hỗ trợ sức khỏe da lông"]',
 17, 1, 1, GETDATE(), GETDATE()
),
-- 18. Blue Buffalo
(18,
 N'Blue Buffalo',
 N'BBF',
 N'Thức ăn thiên nhiên cao cấp cho chó mèo',
 N'Blue Buffalo cung cấp thức ăn khô và ướt thiên nhiên, thành phần chính là thịt thật, trái cây, rau củ, không chứa chất bảo quản, hương liệu nhân tạo. Có các dòng như Life Protection, Wilderness, Basics.',
 2003,
 N'Mỹ',
 N'https://bluebuffalo.com/',
 N'/images/brands/18.png',
 N'["Thịt thật","Không chất bảo quản","Hỗ trợ hệ tiêu hóa","Phân theo dòng Life/Wilderness","Hương vị đa dạng","Phù hợp mọi lứa tuổi","Tăng cường sức khỏe miễn dịch","Chất lượng cao"]',
 18, 1, 1, GETDATE(), GETDATE()
),
-- 19. Wellness Core
(19,
 N'Wellness Core',
 N'WCR',
 N'Dinh dưỡng high‑protein không ngũ cốc từ Mỹ',
 N'Wellness Core là dòng thức ăn không ngũ cốc, giàu protein và chất lượng cao, phù hợp với chó mèo năng động hoặc dị ứng ngũ cốc. Có nhiều lựa chọn grain‑free, canned, và littles.',
 2000,
 N'Mỹ',
 N'https://www.wellnesspetfood.com/',
 N'/images/brands/19.png',
 N'["Grain-free","Protein cao","Không GMO","Phù hợp chó mèo","Hỗ trợ sức khỏe cơ bắp","Dễ tiêu hóa","Đa dạng dòng sản phẩm","Chất lượng cao"]',
 19, 1, 1, GETDATE(), GETDATE()
),
-- 20. Ziwipeak
(20,
 N'Ziwipeak',
 N'ZWP',
 N'Thức ăn sấy lạnh nguồn gốc New Zealand',
 N'Ziwipeak là thức ăn sấy lạnh nguyên chất từ New Zealand, tập trung vào nguồn protein cao cấp, không chứa chất phụ gia hay chất bảo quản, phù hợp với thú cưng yêu chế độ ăn nguyên bản.',
 2004,
 N'New Zealand',
 N'https://www.ziwipeak.com/',
 N'/images/brands/20.png',
 N'["Sấy lạnh","Nguyên liệu tự nhiên","Protein cao","Chỉn chu về chất lượng","Hỗ trợ sức khỏe tiêu hóa","Không chứa chất phụ gia","Phù hợp chế độ ăn nguyên bản","Được tin dùng toàn cầu"]',
 20, 1, 1, GETDATE(), GETDATE()
),
-- 21. CIAO
(21,
 N'CIAO',
 N'CIA',
 N'Snack siêu mềm cho mèo từ Nhật Bản',
 N'CIAO được biết đến với dòng Churu – snack siêu mềm, dạng mousse, tiện lợi và dễ ăn cho mèo. Nhiều chủ yêu thích vì dễ dàng cho thú ăn hoặc tráng mặt.',
 1980,
 N'Nhật Bản',
 N'https://www.inaba-pet.co.jp/ciao/',
 N'/images/brands/21.png',
 N'["Snack dạng mousse","Dễ ăn","Nguồn gốc Nhật","Phổ biến tại VN","Hương vị đa dạng","Thích hợp cho mọi lứa tuổi mèo","Hỗ trợ sức khỏe mèo","Được mèo yêu thích"]',
 21, 1, 1, GETDATE(), GETDATE()
),
-- 22. Temptations
(22,
 N'Temptations',
 N'TMP',
 N'Snack mèo đặc biệt, cực kỳ phổ biến',
 N'Temptations là snack mèo dạng crunch, với hương vị đa dạng và dạng túi dễ dùng. Thương hiệu được ưa chuộng vì giá hấp dẫn, phổ biến khắp toàn cầu.',
 1994,
 N'Mỹ',
 N'https://www.temptations.com/',
 N'/images/brands/22.png',
 N'["Snack crunch","Nhiều hương vị","Giá rẻ","Phổ biến toàn cầu","Dễ sử dụng","Thích hợp cho mọi lứa tuổi mèo","Hỗ trợ sức khỏe răng miệng","Được mèo yêu thích"]',
 22, 1, 1, GETDATE(), GETDATE()
),
-- 23. Canidae
(23,
 N'Canidae',
 N'CND',
 N'Thức ăn tự nhiên chất lượng cao cho chó mèo',
 N'Canidae đưa ra các sản phẩm nguyên liệu tự nhiên, không GMO, một số dòng grain‑free, phù hợp chó mèo mọi lứa tuổi và kích cỡ.',
 1996,
 N'Mỹ',
 N'https://www.canidae.com/',
 N'/images/brands/23.png',
 N'["Natural","Non-GMO","Grain-free","Phù hợp mọi lứa tuổi","Hỗ trợ sức khỏe tiêu hóa","Chất lượng cao","Hương vị đa dạng","Được tin dùng rộng rãi"]',
 23, 1, 1, GETDATE(), GETDATE()
),
-- 24. Purina Pro Plan
(24,
 N'Purina Pro Plan',
 N'PPP',
 N'Dinh dưỡng thú y cao cấp từ Mỹ',
 N'Purina Pro Plan là dòng thức ăn cao cấp của Purina, kết hợp khoa học và chuyên môn thú y, nhiều dòng chuyên biệt Urinary, Sensitive Skin & Stomach…',
 1986,
 N'Mỹ',
 N'https://www.proplan.com/',
 N'/images/brands/24.png',
 N'["Thú y chuyên biệt","Nghiên cứu bởi bác sĩ thú y","Dòng Urinary / Sensitive","Dinh dưỡng khoa học","Hỗ trợ sức khỏe toàn diện","Chất lượng cao","Phù hợp chó mèo","Hiệu quả đã được chứng minh"]',
 24, 1, 1, GETDATE(), GETDATE()
);

-- 4. Tắt lại IDENTITY_INSERT nếu đã bật
SET IDENTITY_INSERT Brands OFF;